# Generated by Django 3.2.3 on 2021-06-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
