# Generated by Django 3.2.3 on 2021-06-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notebook_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='trashed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
