# Generated by Django 3.2.3 on 2021-07-26 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20210726_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 26, 8, 15, 28, 496031, tzinfo=utc)),
        ),
    ]
