# Generated by Django 3.2.3 on 2021-07-29 06:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20210726_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingnote',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 29, 6, 21, 1, 215693, tzinfo=utc)),
        ),
    ]
