# Generated by Django 3.2.3 on 2021-08-20 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20210816_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 20, 10, 8, 31, 603695, tzinfo=utc)),
        ),
    ]
