# Generated by Django 3.2.3 on 2021-08-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_meetingnote_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingnote',
            name='date_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
